---
title: "Quantifying changes in FC in the context of IEDs"
output: html_document
author: Jennifer Stiso
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# clean workspace
rm(list=ls())

if (!require("pacman")) install.packages("pacman")
pacman::p_load(ggplot2, dplyr, lm.beta, RColorBrewer, nationalparkcolors, rjson, reticulate, gridExtra, wesanderson, MASS, outliers, lmerTest, stringr, lmPerm)

# set up python for later
use_python("/Users/stiso/anaconda3/bin/python") # path to python binary
py_config() # check it is using the specified version

# directory for RAM data, request from XXX
RAM_dir = '/Volumes/bassett-data/Jeni/RAM/'

# parameters
win = 1
detector = '_delphos_auto'

```

## Functions
```{r, echo=FALSE, results=FALSE}
get_beta <- function(d, ys, f) {
  # fit models for every given predictor
  for (y in ys){
    # remove nan rows
    d_lm = d[!is.na(d[y]),]
  
    # check if multiple sess and exper
    if (length(unique(d_lm$sess_exper)) > 1) {
      f_full <- paste(f, 'sess_exper', sep = ' + ')
      # to prevent prevent factor level errors
      d_lm$sess_exper = as.factor(d_lm$sess_exper)
    } else {
      f_full <- f
    }
    
    beta_bin_name <- paste(y, 'beta_bin', sep = '_')
    beta_num_name <- paste(y, 'beta_num', sep = '_')
    beta_spr_name <- paste(y, 'beta_spr', sep = '_')
    if (dim(d_lm[y])[1] == 0){ # check for nans
      d[beta_bin_name] <- NaN
      d[beta_num_name] <- NaN
      d[beta_spr_name] <- NaN
    } else {

      # make spike a factor - prevent factor level errors
      d_lm$bin_spike <- as.factor(d_lm$bin_spike)
      # for debugging
      # print(paste(y, d_lm$band[1], d_lm$fc_measure[1], d_lm$region[1]))
      
      # fit
      # check for singular matrix (only two values for spike_num)
      cor_check1 = cor.test(d_lm$spike_num, d_lm$spike_spread) 
      cor_check2 = cor.test(d_lm$spike_num, as.numeric(d_lm$bin_spike))
      if (cor_check1$estimate != 1 & cor_check2$estimate != 1){
        f_full = paste(y, f_full, sep = '')
        try({fit <- lmp(as.formula(f_full), d_lm, singular.ok = FALSE)
        d[beta_bin_name] <- fit$coefficients['bin_spike1']
        d[beta_num_name] <- fit$coefficients['spike_num']
        d[beta_spr_name] <- fit$coefficients['spike_spread']})
      } else if (cor_check1$estimate == 1 & cor_check2$estimate != 1){
        f_full <- str_remove(f_full, fixed("+ spike_spread"))
        f_full = paste(y, f_full, sep = '')
        try({fit <- lmp(as.formula(f_full), d_lm, singular.ok = FALSE)
        d[beta_bin_name] <- fit$coefficients['bin_spike1']
        d[beta_num_name] <- fit$coefficients['spike_num']
        d[beta_spr_name] <- NaN})
      } else if (cor_check2$estimate == 1 & cor_check1$estimate != 1){
        f_full <- str_remove(f_full, fixed("+ bin_spike"))
        f_full = paste(y, f_full, sep = '')
        try({fit <- lmp(as.formula(f_full), d_lm, singular.ok = FALSE)
        d[beta_spr_name] <- fit$coefficients['spike_spread']
        d[beta_num_name] <- fit$coefficients['spike_num']
        d[beta_bin_name] <- NaN})
      } else {
        f_full <- str_remove(f_full, fixed("+ spike_num + spike_spread"))
        f_full = paste(y, f_full, sep = '')
        try({fit <- lmp(as.formula(f_full), d_lm, singular.ok = FALSE)
        d[beta_bin_name] <- fit$coefficients['bin_spike1']
        d[beta_num_name] <- NaN
        d[beta_spr_name] <- NaN})
      }
    }
  }
  return(d)
}
```


## Load Data

```{r}
# get subjects from all releases
releases <- c('1', '2', '3')
subj <- list()
for (r in releases){
  curr_info <- paste(RAM_dir, 'release', r, '/protocols/r1.json', sep='')
  df <- rjson::fromJSON(file = curr_info)
  df <- names(df$protocols$r1$subjects) %>%
    lapply(function(x){paste('release', r, '/r1/', x, sep ='')})
  subj <- append(subj, df)
}

```

## Fit Models

```{r, echo=FALSE,results=FALSE}
# Do we want to make plots? faster if no
save_plot = FALSE

# intiialize, make constants
# constant fields
const_vars <- c('subj', 'hand', 'age', 'gender', 'race')
form <- ' ~ power + bin_spike + spike_num + spike_spread'
ys = c('str', 'str_soz', 'str_not_soz', 'str_spike', 'str_not_spike', "ti", "str_grid", "str_depth", "str_gm", "str_wm")
node_ys = c('str', "ti") # to save space and time, only run the main ys for node data

# final df
col_names <- c("fc_measure", "band", 'band_measure', "subj", "hand", "age", "gender", "race", 'n_tp',
                 'str_beta_bin', 'str_beta_num', 'str_beta_spr', 'ti_beta_bin', 'ti_beta_num', 'ti_beta_spr',
                 'str_soz_beta_bin', 'str_soz_beta_num', 'str_soz_beta_spr',
                 'str_not_soz_beta_bin', 'str_not_soz_beta_num', 'str_not_soz_beta_spr', 
                 'str_spike_beta_bin', 'str_spike_beta_num', 'str_spike_beta_spr',
                 'str_not_spike_beta_bin', 'str_not_spike_beta_num', 'str_not_spike_beta_spr',
                 'str_grid_beta_bin', 'str_grid_beta_num', 'str_grid_beta_spr', 
                 'str_depth_beta_bin', 'str_depth_beta_num', 'str_depth_beta_spr',
                 'str_gm_beta_bin', 'str_gm_beta_num' ,'str_gm_beta_spr',
                 'str_wm_beta_bin', 'str_wm_beta_num', 'str_wm_beta_spr')

net_betas <- data.frame(matrix(ncol = length(col_names), nrow = 0))
colnames(net_betas) = col_names
col_names = c("subj", "fc_measure", "band", 'band_measure', "wm", "n_tp", "elec_in_soz", "elec_spike", 
              "age", "gender", "race", "hand", "type", 'str_beta_bin', 'str_beta_num', 'str_beta_spr', 'ti_beta_bin', 'ti_beta_num', 'ti_beta_spr' )
node_betas <- data.frame(matrix(ncol = length(col_names), nrow = 0))
colnames(node_betas) = col_names

# for each subject, load their data and fit some models
for (s in subj){
  # load strengths from matlab
  curr_csv <- paste(RAM_dir, 'FC/', s, '/win_', as.character(win), '/fc_data', detector, '.csv', sep = '')
  if (file.exists(curr_csv) ){
    node_data <- read.csv(curr_csv, header = TRUE, sep = ",", stringsAsFactors = FALSE,
                          colClasses=c(gender='character', hand='character', race='numeric', age='numeric', spike_num='numeric'))
    if (dim(node_data)[1] > 0){
      cat("\014")
      message(paste('Subj', s)) 
      # add band measure, combined string, for easy indexing (keep separate for plotting)
      node_data <- mutate(node_data, band_measure = paste(band, fc_measure, sep = '_'))
      # add sess_exper for model, dont actually want to model them separately
      node_data <- mutate(node_data, sess_exper = paste(sess, exper, sep = '_'))
      # add binary spike
      node_data$bin_spike = node_data$spike_num > 0
      # there shouldn't be any negative numbers, but if there are skip
      if (any(node_data$spike_num[complete.cases(node_data$spike_num)] < 0)){
        node_data$spike_num[node_data$spike_num < 0] = NaN
        warning("This dataset had negative spike numbers: check the spreadsheet")
        next
      }
      # there shouldn't be any NaNs, but if there are skip
      if (any(is.nan(node_data$spike_num)) | any(is.na(node_data$spike_num))){
        warning("This dataset had NaN spike numbers: check the spreadsheet")
        next
      }
      
      # drop hg phase locking - PLV not interpretable for wide band signals
      node_data <- filter(node_data, band_measure != "hg_plv")
      node_data <- filter(node_data, band_measure != "hg_iplv")
      # remove duplicate time points, if present
      node_data <- node_data %>% distinct()
      
      # get network level strength separated by groups
      net_data <- group_by(node_data, sess_exper, time, spike_num, spike_spread, bin_spike, fc_measure, band, band_measure) %>%
        dplyr::summarise(str = mean(str, na.rm=TRUE), ti = mean(ti, na.rm=TRUE),  power = mean(power))
      # first for spike networks
      tmp_spike = group_by(node_data, elec_in_ict, sess_exper, time, band_measure) %>% 
        dplyr::summarise(str_spike = mean(str_spike, na.rm=TRUE), str_not_spike = mean(str_not_spike, na.rm=TRUE))
      tmp_spike$str_spike[tmp_spike$elec_in_ict == 0] <- NA
      tmp_spike$str_not_spike[tmp_spike$elec_in_ict == 1] <- NA
      tmp_spike <- group_by(tmp_spike, sess_exper, time, band_measure) %>%
        dplyr::summarise(str_spike = mean(str_spike, na.rm=TRUE), str_not_spike = mean(str_not_spike, na.rm=TRUE))
      net_data = merge(net_data, tmp_spike, 
                       by = c('sess_exper', 'time', 'band_measure'))
      # for soz networks
      tmp_soz = group_by(node_data, elec_in_soz, sess_exper, time, band_measure) %>%
        dplyr::summarise(str_soz = mean(str_soz, na.rm=TRUE), str_not_soz = mean(str_not_soz, na.rm=TRUE))
      # remove not soz elecs from str_soz, and visa versa
      tmp_soz$str_soz[tmp_soz$elec_in_soz == 0] <- NA
      tmp_soz$str_not_soz[tmp_soz$elec_in_soz == 1] <- NA
      # now colapse over elec_in_soz
      tmp_soz <- group_by(tmp_soz, sess_exper, time, band_measure) %>%
        dplyr::summarise(str_soz = mean(str_soz, na.rm=TRUE), str_not_soz = mean(str_not_soz, na.rm=TRUE))
      # now merge on shared features (subj, band, time, etc)
      net_data = merge(net_data, tmp_soz, 
                       by = c('sess_exper', 'time', 'band_measure'))
      # repeat this process for grid elecs
      try({
        tmp_type = group_by(node_data, type, sess_exper, time, band_measure) %>%
          dplyr::summarise(str_grid = mean(str_grid, na.rm=TRUE), str_depth = mean(str_depth, na.rm=TRUE))
        tmp_type$str_grid[tmp_type$type != 'G'] <- NA
        tmp_type$str_depth[tmp_type$type != 'D'] <- NA
        tmp_type <- group_by(tmp_type, sess_exper, time, band_measure) %>%
          dplyr::summarise(str_grid = mean(str_grid, na.rm=TRUE), str_depth = mean(str_depth, na.rm=TRUE))
        net_data = merge(net_data, tmp_type, by = c('sess_exper', 'time', 'band_measure'))
      })
      if (!"str_grid" %in% colnames(net_data)){
        net_data$str_grid = NaN
        net_data$str_depth = NaN
      }
      # repeat this process for wm elecs
      try({
      tmp_wm = group_by(node_data, wm, sess_exper, time, band_measure) %>%
        dplyr::summarise(str_gm = mean(str_gm, na.rm=TRUE), str_wm = mean(str_wm, na.rm=TRUE))
      tmp_wm$str_gm[tmp_wm$wm == 1] <- NA
      tmp_wm$str_wm[tmp_wm$wm == 0] <- NA
      tmp_wm <- group_by(tmp_wm, sess_exper, time, band_measure) %>%
        dplyr::summarise(str_gm = mean(str_gm, na.rm=TRUE), str_wm = mean(str_wm, na.rm=TRUE))
      net_data = merge(net_data, tmp_wm, by = c('sess_exper', 'time', 'band_measure'))
      })
      if (!"str_wm" %in% colnames(net_data)){
        net_data$str_wm = NaN
        net_data$str_gm = NaN
      }
      # add constants
      net_data[const_vars] = node_data[const_vars][1,]
      
      # plots
      if (save_plot){
          p1 <- ggplot(data=net_data[net_data$spike_num != 0,], aes(x=spike_num)) + geom_histogram() + theme_minimal()
          p2 <-ggplot(data=net_data[net_data$spike_spread != 0,], aes(x=spike_spread)) + geom_histogram() + theme_minimal()
          p3 <- ggplot(data=net_data[net_data$spike_num != 0,], aes(x=str, color=band, fill=as.factor(fc_measure))) + 
            geom_histogram(alpha=0.7) + theme_minimal() + scale_fill_manual(values=park_palette("GeneralGrant")) + scale_color_grey()
          p <- grid.arrange(p1, p2, p3, nrow=3)
          ggsave(paste(RAM_dir, 'img/models/', net_data$subj, '_net_hist.png', sep=''), plot=p, device = 'png')
      }
    
      # for every fc_meansure and band, fit network model
      try({
        curr_net_beta <- group_by(net_data, band_measure) %>%
          group_modify(~ get_beta(.x,ys, form)) %>%
          dplyr::summarise(n_tp = length(time), str_beta_bin = str_beta_bin[1], str_beta_num = str_beta_num[1], str_beta_spr = str_beta_spr[1], 
                           ti_beta_bin = ti_beta_bin[1], ti_beta_num = ti_beta_num[1], ti_beta_spr = ti_beta_spr[1], 
                           str_soz_beta_bin = str_soz_beta_bin[1],  
                           str_soz_beta_num = str_soz_beta_num[1], str_soz_beta_spr = str_soz_beta_spr[1], 
                           str_not_soz_beta_num = str_not_soz_beta_num[1], 
                           str_spike_beta_num = str_spike_beta_num[1], 
                           str_not_soz_beta_spr = str_not_soz_beta_spr[1],str_not_soz_beta_bin = str_not_soz_beta_bin[1], 
                           str_spike_beta_bin = str_spike_beta_bin[1], str_spike_beta_spr = str_spike_beta_spr[1],
                           str_not_spike_beta_bin = str_not_spike_beta_bin[1],fc_measure = fc_measure[1], 
                           str_not_spike_beta_num = str_not_spike_beta_num[1], str_not_spike_beta_spr = str_not_spike_beta_spr[1], 
                           band = band[1], 
                           str_grid_beta_bin = str_grid_beta_bin[1], str_grid_beta_num = str_grid_beta_num[1], 
                           str_grid_beta_spr = str_grid_beta_spr[1], 
                           str_depth_beta_bin = str_depth_beta_bin[1], str_depth_beta_num = str_depth_beta_num[1], 
                           str_depth_beta_spr = str_depth_beta_spr[1],
                           str_wm_beta_bin = str_wm_beta_bin[1], str_wm_beta_num = str_wm_beta_num[1], str_wm_beta_spr = str_wm_beta_spr[1],
                           str_gm_beta_bin = str_gm_beta_bin[1], str_gm_beta_num = str_gm_beta_num[1], str_gm_beta_spr = str_gm_beta_spr[1])
        curr_net_beta[const_vars] <- net_data[const_vars][1,]
        
        # concatenate
        net_betas <- suppressWarnings(rbind(curr_net_beta, net_betas)) # silence warnings about converting factors to strings
      })
  
      # fit node models
      try({
          curr_node_beta <- group_by(node_data, elec, band_measure) %>%
              group_modify(~ get_beta(.x,node_ys, form)) %>%
              dplyr::summarise(n_tp = length(time), elec_spike = mean(elec_has_spike), 
                               elec_in_soz = elec_in_soz[1], elec_in_ict = elec_in_ict[1], ti_beta_bin = ti_beta_bin[1], ti_beta_num = 
                                 ti_beta_num[1], ti_beta_spr = ti_beta_spr[1], str_beta_spr = 
                                 str_beta_spr[1], str_beta_bin = str_beta_bin[1], str_beta_num = str_beta_num[1],
                           fc_measure = fc_measure[1], band = band[1], region = region[1], x = x[1],
                               y = y[1], z = z[1], type = type[1], wm = wm[1])
            curr_node_beta[const_vars] <- net_data[const_vars][1,]
            
          #  concetenate
          node_betas <- suppressWarnings(rbind(curr_node_beta, node_betas)) # silence warnings about converting factors to strings
        })
     }
  }
}

# save betas
write.csv(net_betas, file = paste(RAM_dir, 'group_analysis/win_', as.character(win), '/network_stats', detector, '.csv', sep=''))
write.csv(node_betas, file = paste(RAM_dir, 'group_analysis/win_', as.character(win), '/node_stats', detector, '.csv', sep=''))

```

Get the average rate per person
```{r}

# final df
rates <- data.frame(subj=character(0), rate=numeric(length=0))



# for each subject, load their data and fit some models
for (s in subj){
  # load strengths from matlab
  curr_csv <- paste(RAM_dir, 'FC/', s, '/win_', as.character(win), '/fc_data', detector, '.csv', sep = '')
  if (file.exists(curr_csv) ){
    node_data <- read.csv(curr_csv, header = TRUE, sep = ",", stringsAsFactors = FALSE,
                          colClasses=c(gender='character', hand='character', race='numeric', age='numeric', 
                                       spike_num='numeric'))
    if (dim(node_data)[1] > 0){
      message(paste('Subj', s)) 
      # add band measure, combined string, for easy indexing (keep separate for plotting)
      node_data <- mutate(node_data, band_measure = paste(band, fc_measure, sep = '_'))
      # add sess_exper for model, dont actually want to model them separately
      node_data <- mutate(node_data, sess_exper = paste(sess, exper, sep = '_'))
      # add session - time variable
      node_data <- mutate(node_data, tid = paste(sess_exper, str(time), sep = '_'))
      # add binary spike
      node_data$bin_spike = node_data$spike_num > 0
      # there shouldn't be any negative numbers, but if there are skip
      if (any(node_data$spike_num[complete.cases(node_data$spike_num)] < 0)){
        node_data$spike_num[node_data$spike_num < 0] = NaN
        warning("This dataset had negative spike numbers: check the spreadsheet")
        next
      }
      # there shouldn't be any NaNs, but if there are skip
      if (any(is.nan(node_data$spike_num)) | any(is.na(node_data$spike_num))){
        warning("This dataset had NaN spike numbers: check the spreadsheet")
        next
      }
      
      # drop hg phase locking - PLV not interpretable for wide band signals
      node_data <- filter(node_data, band_measure != "hg_plv")
      node_data <- filter(node_data, band_measure != "hg_iplv")
      # remove duplicate time points, if present
      node_data <- node_data %>% distinct()
      
      # get network level strength separated by groups
      net_data <- group_by(node_data, tid, spike_num) %>%
        dplyr::summarise(str = mean(str, na.rm=TRUE))
      
      # get rate
      curr_rate = sum(net_data$spike_num)/length(unique(net_data$tid))
      curr_subj = str_split(s, '/')      
      #  concetenate
      rates <- suppressWarnings(bind_rows(data.frame( "subj" =curr_subj[[1]][3], "rate"=curr_rate), rates)) # silence warnings about converting factors to strings
     }
  }
}

# save betas
write.csv(rates, file = paste(RAM_dir, 'group_analysis/win_', as.character(win), '/ied_rate', detector, '.csv', sep=''))

```


Test how spike parameters change 

```{r}

alt_param = '_param1'

# final df
params <- data.frame(subj=character(0), default_num=numeric(length=0), alt_num=numeric(length=0),
                     corr_num=numeric(length=0), default_spr=numeric(length=0), alt_spr=numeric(length=0),
                     corr_spr=numeric(length=0))

# for each subject, load their data and fit some models
for (s in subj){
  # load strengths from matlab
  curr_csv <- paste(RAM_dir, 'FC/', s, '/win_', as.character(win), '/fc_data', detector, '.csv', sep = '')
  alt_csv <- paste(RAM_dir, 'FC/', s, '/win_', as.character(win), '/alt_spikes', alt_param, '.csv', sep = '')
  if (file.exists(curr_csv) ){
    node_data <- read.csv(curr_csv, header = TRUE, sep = ",", stringsAsFactors = FALSE,
                          colClasses=c(gender='character', hand='character', race='numeric', age='numeric', 
                                       spike_num='numeric'))
    alt_data <- read.csv(alt_csv, header = TRUE, sep = ",", stringsAsFactors = FALSE)
    if (dim(node_data)[1] > 0){
      message(paste('Subj', s)) 
      # add band measure, combined string, for easy indexing (keep separate for plotting)
      node_data <- mutate(node_data, band_measure = paste(band, fc_measure, sep = '_'))
      # add sess_exper for model, dont actually want to model them separately
      node_data <- mutate(node_data, sess_exper = paste(sess, exper, sep = '_'))
      alt_data <- mutate(alt_data, sess_exper = paste(sess, exper, sep = '_'))
      # add session - time variable
      node_data <- mutate(node_data, tid = paste(sess_exper, str(time), sep = '_'))
      alt_data <- mutate(alt_data, tid = paste(sess_exper, str(time), sep = '_'))
      # add binary spike
      node_data$bin_spike = node_data$spike_num > 0
      alt_data$bin_spike = alt_data$spike_num > 0
      # there shouldn't be any negative numbers, but if there are skip
      if (any(node_data$spike_num[complete.cases(node_data$spike_num)] < 0)){
        node_data$spike_num[node_data$spike_num < 0] = NaN
        warning("This dataset had negative spike numbers: check the spreadsheet")
        next
      }
      # there shouldn't be any NaNs, but if there are skip
      if (any(is.nan(node_data$spike_num)) | any(is.na(node_data$spike_num))){
        warning("This dataset had NaN spike numbers: check the spreadsheet")
        next
      }
      
      # drop hg phase locking - PLV not interpretable for wide band signals
      node_data <- filter(node_data, band_measure != "hg_plv")
      node_data <- filter(node_data, band_measure != "hg_iplv")
      # remove duplicate time points, if present
      node_data <- node_data %>% distinct()
      
      # get network level strength separated by groups
      try({
        net_data <- group_by(node_data, tid, spike_num, spike_spread, bin_spike) %>%
        dplyr::summarise(str = mean(str, na.rm=TRUE))
        alt_net <- group_by(alt_data, tid, spike_num, spike_spread, bin_spike) %>%
          dplyr::summarise(n = n())
        num_corr = cor.test(net_data$spike_num, alt_net$spike_num, method='spearman')
        spr_corr = cor.test(net_data$spike_spread, alt_net$spike_spread, method='spearman')
        
        #  concetenate
        curr_subj = str_split(s, '/')
        l = length(alt_net$tid)
        params <- suppressWarnings(bind_rows(data.frame( subj=rep(curr_subj[[1]][3],times=l), default_num=net_data$spike_num, 
                                                         alt_num=alt_net$spike_num,corr_num=rep(num_corr$estimate,times=l), 
                                                         default_spr=net_data$spike_spread, alt_spr=alt_net$spike_spread,
                                                         corr_spr=rep(spr_corr$estimate,times=l)), params))# silence warnings about
      })
    }
  }
}

# plot
p1 <- ggplot(data=params, 
             aes(x=alt_num, y=default_num)) + 
            geom_smooth(method='lm') + theme_minimal()
p2 <- ggplot(data=params, 
             aes(x=alt_spr, y=default_spr)) + 
            geom_smooth(method='lm') + theme_minimal()
p3 <- ggplot(data=params, 
             aes(x=corr_num)) + 
            geom_histogram() + theme_minimal()
p4 <- ggplot(data=params, 
             aes(x=corr_spr)) + 
            geom_histogram() + theme_minimal()
g = grid.arrange(p1, p2, p3, p4, nrow=2) 

ggsave(paste(RAM_dir, 'img/models/spike', alt_param, '.pdf', sep=''), g)

```




